// <auto-generated />

using System;
using System.CodeDom.Compiler;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RALE.Server.Data.Migrations;

/// <summary>Adds persisted multi-agent orchestration state to the RALE schema.</summary>
[DbContext(typeof(RALEContext))]
[Migration("20260616150000_MultiAgentOrchestration")]
[GeneratedCode("Microsoft.EntityFrameworkCore.Tools", "10.0.0")]
public sealed partial class MultiAgentOrchestration : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        ArgumentNullException.ThrowIfNull(migrationBuilder);

        migrationBuilder.AddColumn<string>(
            name: "ConstraintsJson",
            table: "Loops",
            type: "TEXT",
            nullable: false,
            defaultValue: "{}");

        migrationBuilder.AddColumn<DateTimeOffset>(
            name: "Deadline",
            table: "Loops",
            type: "TEXT",
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "ExecutionPattern",
            table: "Loops",
            type: "TEXT",
            maxLength: 32,
            nullable: false,
            defaultValue: "serial");

        migrationBuilder.AddColumn<int>(
            name: "IterationLimit",
            table: "Loops",
            type: "INTEGER",
            nullable: false,
            defaultValue: 3);

        migrationBuilder.AddColumn<int>(
            name: "Priority",
            table: "Loops",
            type: "INTEGER",
            nullable: false,
            defaultValue: 0);

        migrationBuilder.AddColumn<string>(
            name: "RequiredArtifactsJson",
            table: "Loops",
            type: "TEXT",
            nullable: false,
            defaultValue: "[]");

        migrationBuilder.AddColumn<bool>(
            name: "ApprovalRequired",
            table: "Goals",
            type: "INTEGER",
            nullable: false,
            defaultValue: false);

        migrationBuilder.AddColumn<string>(
            name: "ApprovalState",
            table: "Goals",
            type: "TEXT",
            maxLength: 32,
            nullable: false,
            defaultValue: "NotRequired");

        // SQLite cannot add a foreign key to an existing table, and EF Core can only rebuild the table when the
        // migration carries a target model. ALTER TABLE ADD COLUMN accepts a REFERENCES clause for a nullable column,
        // so the column and its FK_Goals_Agents_AssignedAgentId constraint are created together.
        migrationBuilder.Sql(
            """
            ALTER TABLE "Goals" ADD COLUMN "AssignedAgentId" TEXT NULL
                CONSTRAINT "FK_Goals_Agents_AssignedAgentId" REFERENCES "Agents" ("Id") ON DELETE SET NULL;
            """);

        migrationBuilder.AddColumn<DateTimeOffset>(
            name: "Deadline",
            table: "Goals",
            type: "TEXT",
            nullable: true);

        migrationBuilder.AddColumn<int>(
            name: "IterationCount",
            table: "Goals",
            type: "INTEGER",
            nullable: false,
            defaultValue: 0);

        migrationBuilder.AddColumn<int>(
            name: "IterationLimit",
            table: "Goals",
            type: "INTEGER",
            nullable: false,
            defaultValue: 3);

        migrationBuilder.AddColumn<DateTimeOffset>(
            name: "LastHeartbeatAt",
            table: "Goals",
            type: "TEXT",
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "PolicyState",
            table: "Goals",
            type: "TEXT",
            maxLength: 32,
            nullable: false,
            defaultValue: "Allowed");

        migrationBuilder.AddColumn<string>(
            name: "PolicyViolationsJson",
            table: "Goals",
            type: "TEXT",
            nullable: false,
            defaultValue: "[]");

        migrationBuilder.AddColumn<int>(
            name: "Priority",
            table: "Goals",
            type: "INTEGER",
            nullable: false,
            defaultValue: 0);

        migrationBuilder.AddColumn<string>(
            name: "RequiredArtifactsJson",
            table: "Goals",
            type: "TEXT",
            nullable: false,
            defaultValue: "[]");

        migrationBuilder.AddColumn<int>(
            name: "RetryCount",
            table: "Goals",
            type: "INTEGER",
            nullable: false,
            defaultValue: 0);

        migrationBuilder.AddColumn<int>(
            name: "RetryLimit",
            table: "Goals",
            type: "INTEGER",
            nullable: false,
            defaultValue: 2);

        migrationBuilder.AddColumn<string>(
            name: "TaskType",
            table: "Goals",
            type: "TEXT",
            maxLength: 128,
            nullable: false,
            defaultValue: "general");

        migrationBuilder.AddColumn<int>(
            name: "CachedCapacity",
            table: "Agents",
            type: "INTEGER",
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "CachedCapacityConstraintsJson",
            table: "Agents",
            type: "TEXT",
            nullable: false,
            defaultValue: "{}");

        migrationBuilder.AddColumn<int>(
            name: "CapacityCacheTtlSeconds",
            table: "Agents",
            type: "INTEGER",
            nullable: false,
            defaultValue: 300);

        migrationBuilder.AddColumn<DateTimeOffset>(
            name: "CapacityCheckedAt",
            table: "Agents",
            type: "TEXT",
            nullable: true);

        migrationBuilder.AddColumn<DateTimeOffset>(
            name: "CapacityExpiresAt",
            table: "Agents",
            type: "TEXT",
            nullable: true);

        migrationBuilder.AddColumn<int>(
            name: "CurrentLoad",
            table: "Agents",
            type: "INTEGER",
            nullable: false,
            defaultValue: 0);

        migrationBuilder.AddColumn<string>(
            name: "Endpoint",
            table: "Agents",
            type: "TEXT",
            maxLength: 512,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<int>(
            name: "MaxConcurrentGoals",
            table: "Agents",
            type: "INTEGER",
            nullable: false,
            defaultValue: 1);

        migrationBuilder.AddColumn<int>(
            name: "MaxTokenCapacity",
            table: "Agents",
            type: "INTEGER",
            nullable: false,
            defaultValue: 4096);

        migrationBuilder.AddColumn<string>(
            name: "SecurityPosture",
            table: "Agents",
            type: "TEXT",
            maxLength: 128,
            nullable: false,
            defaultValue: "unverified");

        migrationBuilder.AddColumn<string>(
            name: "Sla",
            table: "Agents",
            type: "TEXT",
            maxLength: 128,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<string>(
            name: "SupportedTaskTypesJson",
            table: "Agents",
            type: "TEXT",
            nullable: false,
            defaultValue: "[]");

        migrationBuilder.AddColumn<string>(
            name: "ToolScopesJson",
            table: "Agents",
            type: "TEXT",
            nullable: false,
            defaultValue: "[]");

        migrationBuilder.AddColumn<int>(
            name: "TrustLevel",
            table: "Agents",
            type: "INTEGER",
            nullable: false,
            defaultValue: 0);

        migrationBuilder.AddColumn<long>(
            name: "Version",
            table: "Agents",
            type: "INTEGER",
            nullable: false,
            defaultValue: 0L);

        migrationBuilder.CreateTable(
            name: "AgentEvents",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "TEXT", nullable: false),
                AgentId = table.Column<Guid>(type: "TEXT", nullable: false),
                Type = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                Detail = table.Column<string>(type: "TEXT", nullable: false),
                CreatedAt = table.Column<DateTimeOffset>(type: "TEXT", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_AgentEvents", x => x.Id);
                table.ForeignKey(
                    name: "FK_AgentEvents_Agents_AgentId",
                    column: x => x.AgentId,
                    principalTable: "Agents",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "IX_AgentEvents_AgentId",
            table: "AgentEvents",
            column: "AgentId");

        migrationBuilder.CreateIndex(
            name: "IX_Goals_AssignedAgentId",
            table: "Goals",
            column: "AssignedAgentId");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        ArgumentNullException.ThrowIfNull(migrationBuilder);

        // EF Core can only generate DropForeignKey/DropColumn for SQLite by rebuilding the table from a migration
        // target model, which these hand-written migrations do not carry. SQLite 3.35+ drops columns natively, and
        // dropping AssignedAgentId also removes FK_Goals_Agents_AssignedAgentId because it is declared on that column.
        migrationBuilder.DropTable(name: "AgentEvents");
        migrationBuilder.DropIndex(name: "IX_Goals_AssignedAgentId", table: "Goals");

        migrationBuilder.Sql("""ALTER TABLE "Loops" DROP COLUMN "ConstraintsJson";""");
        migrationBuilder.Sql("""ALTER TABLE "Loops" DROP COLUMN "Deadline";""");
        migrationBuilder.Sql("""ALTER TABLE "Loops" DROP COLUMN "ExecutionPattern";""");
        migrationBuilder.Sql("""ALTER TABLE "Loops" DROP COLUMN "IterationLimit";""");
        migrationBuilder.Sql("""ALTER TABLE "Loops" DROP COLUMN "Priority";""");
        migrationBuilder.Sql("""ALTER TABLE "Loops" DROP COLUMN "RequiredArtifactsJson";""");

        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "ApprovalRequired";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "ApprovalState";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "AssignedAgentId";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "Deadline";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "IterationCount";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "IterationLimit";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "LastHeartbeatAt";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "PolicyState";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "PolicyViolationsJson";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "Priority";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "RequiredArtifactsJson";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "RetryCount";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "RetryLimit";""");
        migrationBuilder.Sql("""ALTER TABLE "Goals" DROP COLUMN "TaskType";""");

        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "CachedCapacity";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "CachedCapacityConstraintsJson";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "CapacityCacheTtlSeconds";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "CapacityCheckedAt";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "CapacityExpiresAt";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "CurrentLoad";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "Endpoint";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "MaxConcurrentGoals";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "MaxTokenCapacity";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "SecurityPosture";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "Sla";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "SupportedTaskTypesJson";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "ToolScopesJson";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "TrustLevel";""");
        migrationBuilder.Sql("""ALTER TABLE "Agents" DROP COLUMN "Version";""");
    }
}
